name: Deploy Infrastructure

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      action:
        description: "Choose action: deploy or delete"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - delete

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check template files
        run: |
          ls -l templates/network-stack.cf.yml
          ls -l templates/ecs-stack.cf.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify AWS CLI
        run: |
          aws --version
          aws sts get-caller-identity

      ############################################################
      # DEPLOY SECTION
      ############################################################

      - name: Deploy Network Stack
        if: |
          github.event_name == 'push' ||
          github.event.inputs.action == 'deploy'
        run: |
          aws cloudformation deploy \
            --template-file templates/network-stack.cf.yml \
            --stack-name ecs-network-stack \
            --region us-east-1

      - name: Deploy ECS Stack
        if: |
          github.event_name == 'push' ||
          github.event.inputs.action == 'deploy'
        run: |
          VPC_ID=$(aws cloudformation describe-stacks --stack-name ecs-network-stack --query "Stacks[0].Outputs[?OutputKey=='VpcId'].OutputValue" --output text)
          PUB1=$(aws cloudformation describe-stacks --stack-name ecs-network-stack --query "Stacks[0].Outputs[?OutputKey=='PublicSubnet1Id'].OutputValue" --output text)
          PUB2=$(aws cloudformation describe-stacks --stack-name ecs-network-stack --query "Stacks[0].Outputs[?OutputKey=='PublicSubnet2Id'].OutputValue" --output text)
          PRI1=$(aws cloudformation describe-stacks --stack-name ecs-network-stack --query "Stacks[0].Outputs[?OutputKey=='PrivateSubnet1Id'].OutputValue" --output text)
          PRI2=$(aws cloudformation describe-stacks --stack-name ecs-network-stack --query "Stacks[0].Outputs[?OutputKey=='PrivateSubnet2Id'].OutputValue" --output text)

          aws cloudformation deploy \
            --template-file templates/ecs-stack.cf.yml \
            --stack-name ecs-app-stack \
            --capabilities CAPABILITY_IAM \
            --region us-east-1 \
            --parameter-overrides \
              VpcId=$VPC_ID \
              PublicSubnet1Id=$PUB1 \
              PublicSubnet2Id=$PUB2 \
              PrivateSubnet1Id=$PRI1 \
              PrivateSubnet2Id=$PRI2

      ############################################################
      # DELETE SECTION
      ############################################################

      - name: Delete ECS Stack
        if: github.event.inputs.action == 'delete'
        run: |
          echo "Deleting ECS stack..."
          aws cloudformation delete-stack --stack-name ecs-app-stack --region us-east-1
          aws cloudformation wait stack-delete-complete --stack-name ecs-app-stack

      - name: Delete Network Stack
        if: github.event.inputs.action == 'delete'
        run: |
          echo "Deleting Network stack..."
          aws cloudformation delete-stack --stack-name ecs-network-stack --region us-east-1
          aws cloudformation wait stack-delete-complete --stack-name ecs-network-stack

      - name: Action Completed
        run: |
         echo "Task completed: ${{ github.event.inputs.action || 'deploy' }}"
